name: Build and Release APK

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required to upload a release asset.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build release APK
        # This command builds the APK file.
        run: ./gradlew assembleRelease

      - name: List files in build directory
        run: ls -R app/build/outputs
        
      - name: Upload APK to Release
        # This action uploads the built APK to the release that triggered the workflow.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This gets the URL for uploading assets to the current release
          upload_url: ${{ github.event.release.upload_url }} 
          # This is the path to the file you want to upload
          asset_path: ./app/build/outputs/apk/release/app-release-unsigned.apk
          # This is the name the file will have in the release
          asset_name: webview.apk
          # This is the content type of the asset
          asset_content_type: application/vnd.android.package-archive
